### ISSUE TITLE
Fingerprint updates not available for unavailable contacts at login

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/tigase-extension#15]
Since unavailable presence is not broadcasted when requesting the roster, fingerprint updates are not published at login time. Instead of broadcasting unavailable presences, we could add a fingerprint attribute to the `<item/>` node at node building time (that is, do not store it).

---

https://projects.tigase.org/issues/2530#note-16

**Comment by daniele-athome** [comment]
https://projects.tigase.org/issues/2530#note-9

**Comment by strk** [comment]
milestone to be updated ?

**Comment by daniele-athome** [comment]
It's 1.0-beta1, but the server part release workflow is not well defined yet (meaning to exact ETA).

**Comment by daniele-athome** [comment]
Superseded by #61.
