### ISSUE TITLE
Messages from another another contact are mistreated as own messages

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/tigase-extension#59]
I've been tracking this issue for a few weeks now. I've opened a ticket to Tigase here:
https://projects.tigase.org/issues/3689

I thought I've fixed it in kontalk/tigase-extension@68a378062b89947cb7ddb903a03b77a3a7822afe, apparently it wasn't fixed.

**Comment by Manizuca** [comment]
This happened to me just 7 minutes ago, something that i can do to help?

**Comment by daniele-athome** [comment]
Thanks @Manizuca, for the moment I'm waiting for a reply from the Tigase team (see related issue URL above)

**Comment by daniele-athome** [comment]
The Tigase team finally [solved the issue](https://projects.tigase.org/projects/tigase-server/repository/revisions/491bb0f6a652ea30df8ff842afcb8171cfa6bcf7). I will install the patch ASAP (possibly tonight).

**Comment by daniele-athome** [comment]
No longer happened for over a month now. Closing.
